# Generated by Django 4.2.21 on 2025-05-28 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0003_emailotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="closing_time",
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name="store",
            name="opening_time",
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
